# Generated by Django 6.0.3 on 2026-05-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_menuitem_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
