# Generated by Django 6.0.3 on 2026-09-17 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreference',
            options={'verbose_name': 'تفضيل المستخدم', 'verbose_name_plural': 'تفضيلات المستخدم'},
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='notify_email',
            field=models.BooleanField(default=True, verbose_name='إشعارات البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='notify_order_updates',
            field=models.BooleanField(default=True, verbose_name='إشعارات تحديث الطلبات'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='notify_promotions',
            field=models.BooleanField(default=True, verbose_name='الإشعارات الترويجية'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='theme',
            field=models.CharField(choices=[('light', 'فاتح'), ('dark', 'داكن'), ('system', 'تلقائي')], default='light', max_length=10, verbose_name='المظهر'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
