# Generated by Django 6.0.3 on 2026-06-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_global_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='النص الفرعي')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='الصورة')),
                ('cta_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='نص الزر')),
                ('cta_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='رابط الزر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعلان رئيسي',
                'verbose_name_plural': 'الإعلانات الرئيسية',
            },
        ),
    ]
