# Generated by Django 6.0.3 on 2026-06-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_herobanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=models.FileField(null=True, upload_to='banners/', verbose_name='الصورة أو الفيديو'),
        ),
    ]
