# Generated by Django 6.0.3 on 2026-06-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_herobanner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='text_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='لون النص'),
        ),
    ]
