# Generated by Django 6.0.3 on 2026-06-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_herobanner_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_trendy',
            field=models.BooleanField(default=False, verbose_name='رائج'),
        ),
    ]
