# Generated by Django 6.0.3 on 2026-06-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_category_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_title', models.CharField(default='أهلاً بك في طعميني', max_length=255, verbose_name='عنوان الترحيب')),
                ('welcome_subtitle', models.TextField(default='اكتشف الوجبات الأقرب إليك واستمتع بتجربة توصيل سريعة.', verbose_name='النص الترحيبي')),
            ],
            options={
                'verbose_name': 'محتوى الموقع',
                'verbose_name_plural': 'محتوى الموقع',
            },
        ),
    ]
