# Generated by Django 6.0.3 on 2026-06-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_sitecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='welcome_verse',
            field=models.TextField(default='يَا أَيُّهَا الَّذِينَ آمَنُوا كُلُوا مِن طَيِّبَاتِ مَا رَزَقْنَاكُمْ وَاشْكُرُوا لِلَّهِ إِن كُنتُمْ إِيَّاهُ تَعْبُدُونَ', verbose_name='الآية الترحيبية'),
        ),
    ]
