# Generated by Django 6.0.3 on 2026-06-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_sitecontent_welcome_verse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontent',
            name='welcome_verse',
        ),
    ]
