# Generated by Django 6.0.3 on 2026-06-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_remove_sitecontent_welcome_verse'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='welcome_subtitle_color',
            field=models.CharField(default='#6b7280', help_text='Hex colour code e.g. #6b7280', max_length=7, verbose_name='لون النص الترحيبي'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='welcome_title_color',
            field=models.CharField(default='#f97316', help_text='Hex colour code e.g. #f97316', max_length=7, verbose_name='لون عنوان الترحيب'),
        ),
    ]
