# Generated by Django 6.0.3 on 2026-06-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_sitecontent_welcome_subtitle_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='welcome_subtitle_size',
            field=models.CharField(default='1rem', help_text='CSS font-size e.g. 1rem or 16px', max_length=10, verbose_name='حجم النص الترحيبي'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='welcome_title_size',
            field=models.CharField(default='1.875rem', help_text='CSS font-size e.g. 1.875rem or 24px', max_length=10, verbose_name='حجم عنوان الترحيب'),
        ),
    ]
