# Generated by Django 6.0.3 on 2026-06-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_sitecontent_welcome_subtitle_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='subtitle_size',
            field=models.CharField(default='1rem', help_text='CSS font-size e.g. 1rem or 16px', max_length=10, verbose_name='حجم النص الفرعي'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='title_size',
            field=models.CharField(default='1.5rem', help_text='CSS font-size e.g. 1.5rem or 24px', max_length=10, verbose_name='حجم العنوان'),
        ),
    ]
