# Generated by Django 6.0.3 on 2026-06-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_herobanner_subtitle_size_herobanner_title_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herobanner',
            name='text_color',
        ),
        migrations.AddField(
            model_name='herobanner',
            name='subtitle_color',
            field=models.CharField(default='#ffffff', help_text='Hex colour code e.g. #ffffff', max_length=7, verbose_name='لون النص الفرعي'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='title_color',
            field=models.CharField(default='#ffffff', help_text='Hex colour code e.g. #ffffff', max_length=7, verbose_name='لون العنوان'),
        ),
    ]
