# Generated by Django 6.0.3 on 2026-06-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_remove_herobanner_text_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='cta_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نص الزر'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='cta_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نص الزر'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='subtitle_ar',
            field=models.TextField(blank=True, null=True, verbose_name='النص الفرعي'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='subtitle_en',
            field=models.TextField(blank=True, null=True, verbose_name='النص الفرعي'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='welcome_subtitle_ar',
            field=models.TextField(default='اكتشف الوجبات الأقرب إليك واستمتع بتجربة توصيل سريعة.', null=True, verbose_name='النص الترحيبي'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='welcome_subtitle_en',
            field=models.TextField(default='اكتشف الوجبات الأقرب إليك واستمتع بتجربة توصيل سريعة.', null=True, verbose_name='النص الترحيبي'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='welcome_title_ar',
            field=models.CharField(default='أهلاً بك في طعميني', max_length=255, null=True, verbose_name='عنوان الترحيب'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='welcome_title_en',
            field=models.CharField(default='أهلاً بك في طعميني', max_length=255, null=True, verbose_name='عنوان الترحيب'),
        ),
    ]
