# Generated by Django 6.0.3 on 2026-06-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0019_category_name_ar_category_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='name_en',
        ),
    ]
