# Generated by Django 6.0.3 on 2026-06-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0020_remove_restaurant_name_ar_remove_restaurant_name_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name_en',
        ),
    ]
