# Generated by Django 6.0.3 on 2026-07-09 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0021_remove_category_name_ar_remove_category_name_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobanner',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='discount_price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_trendy',
            field=models.BooleanField(db_index=True, default=False, verbose_name='رائج'),
        ),
        migrations.AddIndex(
            model_name='herobanner',
            index=models.Index(fields=['is_active'], name='restaurants_is_acti_e8b6b6_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['restaurant', 'is_available'], name='restaurants_restaur_1087ee_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['restaurant', 'category'], name='restaurants_restaur_8b6548_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['is_approved', 'is_trendy'], name='restaurants_is_appr_847bd9_idx'),
        ),
    ]
