# Generated by Django 6.0.3 on 2026-08-12 10:24

import tamini.media
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0022_alter_herobanner_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=tamini.media.OptimizedImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=tamini.media.OptimizedMediaField(null=True, upload_to='banners/', verbose_name='الصورة أو الفيديو'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=tamini.media.OptimizedImageField(blank=True, null=True, upload_to='menu_items/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cover_image',
            field=tamini.media.OptimizedImageField(blank=True, null=True, upload_to='restaurant_covers/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=tamini.media.OptimizedImageField(blank=True, null=True, upload_to='restaurant_logos/'),
        ),
    ]
