# Generated by Django 6.0.3 on 2026-08-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0023_alter_category_image_alter_herobanner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Delivery fee'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_fee_per_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Delivery fee per km'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_radius_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Delivery radius (km)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='has_own_delivery',
            field=models.BooleanField(default=True, verbose_name='Own delivery'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Min order amount'),
        ),
    ]
