# Generated by Django 6.0.3 on 2026-08-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0025_strip_media_prefix_from_file_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['restaurant'], name='restaurants_restaur_de52fc_idx'),
        ),
    ]
