# Generated by Django 6.0.3 on 2026-09-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0026_category_restaurants_restaur_de52fc_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='privacy_policy',
            field=models.TextField(blank=True, help_text='يُعرض في صفحة سياسة الخصوصية /legal/privacy/ (يدعم HTML)', verbose_name='سياسة الخصوصية'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='privacy_policy_ar',
            field=models.TextField(blank=True, help_text='يُعرض في صفحة سياسة الخصوصية /legal/privacy/ (يدعم HTML)', null=True, verbose_name='سياسة الخصوصية'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='privacy_policy_en',
            field=models.TextField(blank=True, help_text='يُعرض في صفحة سياسة الخصوصية /legal/privacy/ (يدعم HTML)', null=True, verbose_name='سياسة الخصوصية'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='terms_of_service',
            field=models.TextField(blank=True, help_text='يُعرض في صفحة شروط الخدمة /legal/terms/ (يدعم HTML)', verbose_name='شروط الخدمة'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='terms_of_service_ar',
            field=models.TextField(blank=True, help_text='يُعرض في صفحة شروط الخدمة /legal/terms/ (يدعم HTML)', null=True, verbose_name='شروط الخدمة'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='terms_of_service_en',
            field=models.TextField(blank=True, help_text='يُعرض في صفحة شروط الخدمة /legal/terms/ (يدعم HTML)', null=True, verbose_name='شروط الخدمة'),
        ),
    ]
