# Generated by Django 6.0.3 on 2026-09-17 10:12

import django.db.models.deletion
import tamini.media
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0027_sitecontent_privacy_policy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'فئة', 'verbose_name_plural': 'الفئات'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'عنصر قائمة', 'verbose_name_plural': 'عناصر القائمة'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'مطعم', 'verbose_name_plural': 'المطاعم'},
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=tamini.media.OptimizedImageField(blank=True, null=True, upload_to='categories/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurants.restaurant', verbose_name='المطعم'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.category', verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='discount_price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر بعد التخفيض'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=tamini.media.OptimizedImageField(blank=True, null=True, upload_to='menu_items/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='متاح'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant', verbose_name='المطعم'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address_ar',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address_en',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cover_image',
            field=tamini.media.OptimizedImageField(blank=True, null=True, upload_to='restaurant_covers/', verbose_name='الصورة الغلاف'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم التوصيل'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_fee_per_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم التوصيل لكل كم'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_radius_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='نصف قطر التوصيل (كم)'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='has_own_delivery',
            field=models.BooleanField(default=True, verbose_name='توصيل خاص'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, verbose_name='مقبول'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='خط العرض'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=tamini.media.OptimizedImageField(blank=True, null=True, upload_to='restaurant_logos/', verbose_name='الشعار'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='خط الطول'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأدنى للطلب'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم المطعم'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL, verbose_name='المالك'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
    ]
