# Generated by Django 6.0.3 on 2026-06-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment_ar',
            field=models.TextField(blank=True, null=True, verbose_name='التعليق'),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_en',
            field=models.TextField(blank=True, null=True, verbose_name='التعليق'),
        ),
    ]
