# Generated by Django 6.0.3 on 2026-06-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_review_comment_ar_review_comment_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_order_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم الطلب للعميل'),
        ),
    ]
