# Generated by Django 6.0.3 on 2026-06-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_customer_order_number_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_order_number',
        ),
    ]
