# Generated by Django 6.0.3 on 2026-06-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_customer_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_order_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم الطلب للعميل'),
        ),
    ]
