# Generated by Django 6.0.3 on 2026-08-26 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['customer', 'is_active'], name='orders_tick_custome_c1a14d_idx'),
        ),
    ]
