# Generated by Django 6.0.3 on 2026-09-17 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_cart_unique_constraints_collapse_duplicates'),
        ('restaurants', '0028_alter_category_options_alter_menuitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'سلة', 'verbose_name_plural': 'السلال'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'عنصر سلة', 'verbose_name_plural': 'عناصر السلة'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'طلب', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'عنصر طلب', 'verbose_name_plural': 'عناصر الطلبات'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='معرّف الجلسة'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart', verbose_name='السلة'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.menuitem', verbose_name='العنصر'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(verbose_name='عنوان التوصيل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم التوصيل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='خط عرض التوصيل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='خط طول التوصيل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.restaurant', verbose_name='المطعم'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'قيد الانتظار'), ('Confirmed', 'مؤكد'), ('Preparing', 'قيد التحضير'), ('Out for Delivery', 'في الطريق للتوصيل'), ('Delivered', 'تم التوصيل'), ('In Progress', 'قيد التنفيذ'), ('Completed', 'مكتمل'), ('Cancelled', 'ملغي')], db_index=True, default='Pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي السعر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.menuitem', verbose_name='العنصر'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.restaurant', verbose_name='المطعم'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
