# Generated by Django 6.0.3 on 2026-07-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_ensure_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'customer'), ('restaurant', 'restaurant'), ('delivery', 'delivery'), ('admin', 'admin')], db_index=True, default='customer', max_length=20),
        ),
    ]
