# Generated by Django 6.0.3 on 2026-09-17 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_pendingsignup'),
        ('restaurants', '0028_alter_category_options_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingsignup',
            options={'verbose_name': 'طلب تسجيل قيد المراجعة', 'verbose_name_plural': 'طلبات تسجيل قيد المراجعة'},
        ),
        migrations.AlterField(
            model_name='pendingsignup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='pendingsignup',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='pendingsignup',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='pendingsignup',
            name='role',
            field=models.CharField(choices=[('customer', 'عميل'), ('restaurant', 'مطعم'), ('delivery', 'سائق')], max_length=20, verbose_name='الدور'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='مقبول'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='موثّق'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='user',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='restaurants.restaurant', verbose_name='المطعم'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'عميل'), ('restaurant', 'مطعم'), ('staff', 'موظف'), ('delivery', 'سائق'), ('admin', 'مدير')], db_index=True, default='customer', max_length=20, verbose_name='الدور'),
        ),
    ]
