# Generated by Django 6.0.3 on 2026-09-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_pendingsignup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='معرّف Firebase'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='رمز التحقق'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت إنشاء رمز التحقق'),
        ),
    ]
