# Generated by Django 6.0.3 on 2026-06-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery_is_settled_driverprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('searching', 'Searching'), ('on_way', 'On Way'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered')], db_index=True, default='searching', max_length=20),
        ),
    ]
