# Generated by Django 6.0.3 on 2026-07-09 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_delivery_status'),
        ('orders', '0014_alter_order_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='is_settled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['delivery_person', 'status'], name='delivery_de_deliver_469b35_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['delivery_person', '-updated_at'], name='delivery_de_deliver_58e402_idx'),
        ),
    ]
