# Generated by Django 6.0.3 on 2026-09-17 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_delivery_is_settled_alter_delivery_updated_at_and_more'),
        ('orders', '0017_alter_cart_options_alter_cartitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'توصيلة', 'verbose_name_plural': 'التوصيلات'},
        ),
        migrations.AlterModelOptions(
            name='driverprofile',
            options={'verbose_name': 'ملف سائق', 'verbose_name_plural': 'ملفات السائقين'},
        ),
        migrations.AlterField(
            model_name='delivery',
            name='current_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='خط العرض الحالي'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='current_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='خط الطول الحالي'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='السائق'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='is_settled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='تم التسوية'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('searching', 'جاري البحث'), ('on_way', 'في الطريق'), ('picked_up', 'تم الاستلام'), ('delivered', 'تم التوصيل')], db_index=True, default='searching', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='مقبول'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
