# Generated by Django 6.0.3 on 2026-06-04 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_order_customer_name_order_customer_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='اسم المرسل')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('subject', models.CharField(max_length=255, verbose_name='الموضوع')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'قيد المعالجة'), ('resolved', 'تم الحل'), ('closed', 'مغلق')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('urgent', 'عاجل')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='orders.order')),
            ],
            options={
                'verbose_name': 'تذكرة دعم',
                'verbose_name_plural': 'تذاكر الدعم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.ticket')),
            ],
            options={
                'verbose_name': 'رسالة دعم',
                'verbose_name_plural': 'رسائل الدعم',
                'ordering': ['created_at'],
            },
        ),
    ]
