# Generated by Django 6.0.3 on 2026-06-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='taminyfood@gmail.com', max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(default='+963 900 000 000', max_length=30, verbose_name='رقم الهاتف')),
                ('whatsapp', models.CharField(default='963900000000', max_length=30, verbose_name='رقم واتساب')),
                ('instagram', models.URLField(default='https://instagram.com/taminy', verbose_name='إنستغرام')),
                ('facebook', models.URLField(default='https://facebook.com/taminy', verbose_name='فيسبوك')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
    ]
