# Generated by Django 6.0.3 on 2026-06-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='snapchat',
            field=models.URLField(default='https://snapchat.com/add/taminy', verbose_name='سناب شات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok',
            field=models.URLField(default='https://tiktok.com/@taminy', verbose_name='تيك توك'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='x',
            field=models.URLField(default='https://x.com/taminy', verbose_name='X (تويتر)'),
        ),
    ]
