# Generated by Django 6.0.3 on 2026-06-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_sitesettings_snapchat_sitesettings_tiktok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_base_fee',
            field=models.PositiveIntegerField(default=200, verbose_name='أجرة التوصيل الأساسية (ل.س)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_per_km_fee',
            field=models.PositiveIntegerField(default=1500, verbose_name='أجرة التوصيل لكل كم (ل.س)'),
        ),
    ]
