# Generated by Django 6.0.3 on 2026-06-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_sitesettings_delivery_base_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='commission_rate',
            field=models.PositiveSmallIntegerField(default=12, help_text='مثلاً 12 يعني 12%', verbose_name='نسبة العمولة (%)'),
        ),
    ]
