# Generated by Django 6.0.3 on 2026-06-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_sitesettings_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='description_en',
            field=models.TextField(null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subject_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='الموضوع'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subject_en',
            field=models.CharField(max_length=255, null=True, verbose_name='الموضوع'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='message_ar',
            field=models.TextField(null=True, verbose_name='الرسالة'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='message_en',
            field=models.TextField(null=True, verbose_name='الرسالة'),
        ),
    ]
