# Generated by Django 6.0.3 on 2026-06-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_ticket_description_ar_ticket_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='مفتاح Stripe العام (pk_test)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_secret_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='مفتاح Stripe السري (sk_test)'),
        ),
    ]
