# Generated by Django 6.0.3 on 2026-06-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_sitesettings_stripe_publishable_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_currency',
            field=models.CharField(default='usd', max_length=3, verbose_name='عملة Stripe'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_exchange_rate',
            field=models.PositiveIntegerField(default=13000, help_text='مثلاً 13000 يعني 1 دولار = 13000 ل.س', verbose_name='سعر الصرف (ل.س لكل 1 من عملة Stripe)'),
        ),
    ]
