# Generated by Django 6.0.3 on 2026-06-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_sitesettings_stripe_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_webhook_secret',
            field=models.CharField(blank=True, default='', help_text='من لوحة تحكم Stripe → Webhooks → توقيع السر (Signing secret)', max_length=255, verbose_name='مفتاح Webhook السري (whsec_)'),
        ),
    ]
