# Generated by Django 6.0.3 on 2026-09-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_alter_ticket_priority_alter_ticket_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_mode',
            field=models.CharField(choices=[('enabled', 'مفعل'), ('disabled', 'معطل')], default='enabled', max_length=20, verbose_name='حالة Stripe'),
        ),
    ]
