# Generated by Django 6.0.3 on 2026-09-17 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0011_sitesettings_stripe_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='من يستلم هذه التذكرة من فريق الدعم. تظهر التذاكر غير المحالة فقط في قائمة الانتظار.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='الوكيل المسؤول'),
        ),
    ]
