# Generated by Django 6.0.3 on 2026-06-15 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery_is_settled_driverprofile'),
        ('orders', '0006_order_delivery_fee'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('restaurant', 'Restaurant Commission'), ('delivery', 'Delivery Commission')], max_length=20, verbose_name='نوع العمولة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('is_settled', models.BooleanField(default=False, verbose_name='تم التسوية')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسوية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='delivery.delivery', verbose_name='التوصيل')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'عمولة',
                'verbose_name_plural': 'العمولات',
                'ordering': ['-created_at'],
            },
        ),
    ]
