# Generated by Django 6.0.3 on 2026-06-30 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentgateway_payment_gateway_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentGateway',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='gateway_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_session_id',
        ),
    ]
