# Generated by Django 6.0.3 on 2026-07-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_delivery_is_settled_alter_delivery_updated_at_and_more'),
        ('orders', '0014_alter_order_created_at_and_more'),
        ('payments', '0004_delete_paymentgateway_remove_payment_gateway_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='commission_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant Commission'), ('delivery', 'Delivery Commission')], db_index=True, max_length=20, verbose_name='نوع العمولة'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='is_settled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='تم التسوية'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(db_index=True, default='Card', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['commission_type', 'is_settled'], name='payments_co_commiss_a68be6_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['order'], name='payments_co_order_i_a81f30_idx'),
        ),
    ]
