# Generated by Django 6.0.3 on 2026-09-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_commission_commission_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('cash', 'Cash')], db_index=True, default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_ref',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
