# Generated by Django 6.0.3 on 2026-09-17 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_cart_options_alter_cartitem_options_and_more'),
        ('payments', '0006_payment_exchange_rate_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'دفعة', 'verbose_name_plural': 'الدفعات'},
        ),
        migrations.AlterField(
            model_name='commission',
            name='commission_type',
            field=models.CharField(choices=[('restaurant', 'عمولة المطعم'), ('delivery', 'عمولة التوصيل')], db_index=True, max_length=20, verbose_name='نوع العمولة'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='سعر الصرف'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('cash', 'نقداً')], db_index=True, default='cash', max_length=20, verbose_name='الطريقة'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(db_index=True, default='Card', max_length=50, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_ref',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='مرجع المزوّد'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'قيد الانتظار'), ('Completed', 'مكتمل'), ('Failed', 'فشل')], db_index=True, default='Pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='معرّف العملية'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
    ]
